[package]
name = "core-text"
version = "10.0.0"
authors = ["The Servo Project Developers"]
description = "Bindings to the Core Text framework."
license = "MIT/Apache-2.0"
repository = "https://github.com/servo/core-text-rs"

[features]
default = ["mountainlion"]
# For OS X 10.7 compat, exclude this feature. It will exclude some things from
# the exposed APIs in the crate.
mountainlion = []

[dependencies]
foreign-types = "0.3"
libc = "0.2"
core-foundation = "0.5"
core-graphics = "0.13"
